repos:
  - repo: local
    hooks:
      - id: reformat
        name: Run make reformat
        entry: make reformat
        language: system
        pass_filenames: false
        description: "Format code using black and isort via make reformat"
